# Generated by Django 4.1 on 2022-08-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KOPPEE', '0003_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='Image/'),
            preserve_default=False,
        ),
    ]
