# Generated by Django 4.1 on 2022-08-10 09:51

import KOPPEE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KOPPEE', '0004_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=KOPPEE.models.upload_image),
        ),
    ]
